// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgmpoueddbjfgsaqbmrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbXBvdWVkZGJqZmdzYXFibXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTMwODIsImV4cCI6MjA3NDU2OTA4Mn0.2cx41qsTux8mjbbr0go1xjd9-5wYGrrXyvqXnbQ1wxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});